config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  resources :searches, only: [:index]
  resources :users do
    resources :user_files, except: [:index, :show]
    resources :pdfs, except: [:index, :show]
  end
  resources :users do
    member do
      put "like", to: "users#like"
      put "dislike", to: "users#dislike"
    end
  end
  namespace :admin do
    resources :users, only: [:index]
  end

  resources :charts, only: [:index]
  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  acts_as_votable
  acts_as_voter

  mount_uploader :profile_photo, ProfilePhotoUploader

  has_many :user_arts
  has_many :user_files
  has_many :pdfs
  has_many :art_types, through: :user_arts
  has_many :project_memberships
  has_many :projects, through: :project_memberships
  accepts_nested_attributes_for :art_types
  accepts_nested_attributes_for :user_arts
  has_many :conversations, foreign_key: :sender_id

  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :username, presence: true

  def is_admin?
    role == 'admin'
  end

  include PgSearch
  pg_search_scope :search,
    against: [:first_name, :last_name, :username, :description, :city, :state,
              :website],
    associated_against: { art_types: :name },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorize_admin!
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:q] == ''
      flash.now[:alert] = 'Please specify a search phrase.'
    end
    if params[:q].present?
      @users = User.search(params[:q])
      if @users.empty?
        flash.now[:notice] = 'Sorry, there were no matches.'
      else
        flash.now[:notice] = 'Check out your search matches below!'
      end
    else
      @users = User.all
    end
  end

  def show
    @user = User.find(params[:id])
    @user_files = @user.user_files
    @pdfs = @user.pdfs
    @art_types = @user.art_types
  end

  def edit
    @user = User.find(params[:id])
    @art_types = ArtType.all
    @user_arts = UserArt.new
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)

      id_array = params[:user][:art_type_ids]

      id_array.each do |art_id|
        UserArt.find_or_create_by(user_id: @user.id, art_type_id: art_id)
      end


      flash[:success] = "User updated."
      redirect_to user_path(@user)
    else
      flash[:alert] = @user.errors.full_messages.join(".  ")
      render :edit
    end
  end

  def like
    @user = User.find(params[:id])
    @user.liked_by current_user
    if request.xhr?
      UserMailer.new_vote(@user, current_user).deliver_now
      render json: { count: @user.get_likes.size, id: params[:id] }
    else
      redirect_to @user
    end
  end

  def dislike
    @user = User.find(params[:id])
    @user.disliked_by current_user

    if request.xhr?
      render json: { count: @user.get_likes.size, id: params[:id] }
    else
      redirect_to @user
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :encrypted_password,
      :username,
      :first_name,
      :last_name,
      :description,
      :city,
      :state,
      :website,
      :profile_photo,
      # user_arts_attributes: [:id, :name, art_type_attributes: [:id]],
      art_type_ids: []
    )
  end
end

app/views/users/edit.html.erb
<div class="row">
  <div class="columns large-12">
  <h1>
    Edit your profile and describe yourself and your art.
  </h1>


    <div class="panel">
    <%= form_for @user do |f| %>

      <%= f.label :first_name %>
      <%= f.text_area :first_name %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :description, "About Me" %>
      <%= f.text_area :description %>

      <%= fields_for "user", @art_type do |art_form| %>
        <%= art_form.label "Select your art forms" %>
        <%= art_form.collection_check_boxes :art_type_ids,
        @art_types, :id, :name %>
      <% end %>

      <%= f.label :profile_photo, "Profile Photo" %><br />
      <%= f.file_field :profile_photo %>

      <%= f.submit "Edit Profile", class: "button small radius"  %>

    <%- end -%>
  </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="columns large-12">
    <div class="small-10 small-offset-1 columns">
      <div class="index_head">
        <h3>Want to work with someone on a creative project?
          Find users and projects that match your interests.</h3>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
    <div class="img_space"><%= image_tag "SplitShire-1233.jpg" %></div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="columns small-2">
    <div class="img_space">
      <%= image_tag(@user.profile_photo_url(:thumb)) %>
    </div>
  </div>
  <div class="columns small-10">
    <h1> <%= @user.username %> </h1>
  </div>
</div>

<div class="row">
  <div class="columns small-12">
    <% if current_user && current_user.id != @user.id %>
      <% if current_user.liked? @user %>
        <%= link_to "Undo", dislike_user_path(@user), class: 'vote', method: :put, remote: true %>
      <% else %>
        <%= link_to "Favorite", like_user_path(@user), class: 'vote', method: :put, remote: true %>
      <% end %>
    <% end %>
    <span class="votes-count" data-id="<%= @user.id %>">
      <%= @user.get_likes.size %>
    </span>
    favorites.
  </div>
</div>

<% if current_user && current_user.id == @user.id %>
  <ul class="button-group">
    <li><%= link_to "Edit Profile", edit_user_path(@user), class: "special_button button tiny radius" %></li>
    <li><%= link_to "Add an Image", new_user_user_file_path(@user), class: "special_button button tiny" %></li>
    <li><%= link_to "Add a PDF", new_user_pdf_path(@user), class: "special_button button tiny" %></li>
  </ul>
<% end %>


<div class="panel bio">
  <h3>Bio</h3>

  <b>First name:</b> <%= @user.first_name %><br />
  <b>Last name:</b> <%= @user.last_name %><br />
  <b>Email:</b> <%= @user.email %><br />
  <b>City:</b> <%= @user.city %><br />
  <b>State:</b> <%= @user.state %><br />
  <% if @user.website != nil %>
    <b>Website:</b> <a href="<%= @user.website %>"><%= @user.website %></a><br />
  <% end %>
  <% if @user.description != nil %>
      <b>About me:</b> <%= @user.description %><br />
  <% end %>
  <% if !@art_types.empty? %>
    <b>Art types:</b>
    <ul>
      <div class="art_type_li">
        <% @art_types.each do |art| %>
          <li><%= art.name %></li>
        <% end %>
      </div>
    </ul>
  <% end %>
</div>


<ul class="accordion" data-accordion>
  <% if !@pdfs.empty? %>
    <li class="accordion-navigation">
      <a href="#panel1a">Document Portfolio</a>
      <div id="panel1a" class="content">
        <% @pdfs.each do |pdf| %>
          <div class="pdf_stuff">
            <div class='user_number' style="visibility: collapse">
              <%= @user.id %>
            </div>
            <div class='pdf_number' style="visibility: collapse">
              <%= pdf.id %>
            </div>
            <%= link_to pdf.name, pdf.user_pdf_url %><br>
            <% if current_user && current_user.id == @user.id %>
              <%= link_to "Change", edit_user_pdf_path(@user, pdf),
                class: "button tiny radius" %>
              <%= link_to "Delete", user_pdf_path(@user, pdf),
                method: :delete, class: "button tiny radius" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
  <% if !@user_files.empty? %>
    <li class="accordion-navigation">
      <a href="#panel2a">Visual Portfolio</a>
      <div id="panel2a" class="content">
        <ul class="small-block-grid-2 medium-block-grid-3 large-block-grid-4">
          <% @user_files.each do |file| %>
            <li>
              <div class='user_number' style="visibility: collapse">
                <%= @user.id %>
              </div>
              <div class='user_file_number' style="visibility: collapse">
                <%= file.id %>
              </div>

              <%= image_tag(file.file_url(:showcase)) %><br>

              <% if current_user && current_user.id == @user.id %>
                <%= link_to "Change", edit_user_user_file_path(@user, file),
                  class: "portfolio button tiny radius" %>
                <%= link_to "Delete", user_user_file_path(@user, file),
                  method: :delete, class: "portfolio button tiny radius" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </li>
  <% end %>
</ul>