config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  resources :searches, only: [:index]
  resources :users do
    resources :user_files, except: [:index, :show]
    resources :pdfs, except: [:index, :show]
  end
  resources :users do
    member do
      put "like", to: "users#like"
      put "dislike", to: "users#dislike"
    end
  end
  namespace :admin do
    resources :users, only: [:index]
  end

  resources :charts, only: [:index]
  end

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">Make With Me</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li class="has-form">
        <div class="row collapse">
          <%= form_tag searches_path, method: :get do %>
            <div class="large-8 small-8 columns">
              <%= text_field_tag :q, params[:q] %>
            </div>
            <div class="large-4 small-4 columns">
              <%= submit_tag 'Search', class: "tiny button expand" %>
            </div>
            <% end %>
          </div>
      </li>
      <li><%= link_to 'Art Chart', charts_path %></li>
      <%- if current_user -%>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to current_user.username, user_path(current_user) %></li>
      <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Make With Me</title>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Cabin" %>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/nav" %>

  <% flash.keys.each do |type| %>
    <div data-alert class="flash <%= type %> alert-box radius">
      <%= flash[type] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>

    <div class="row">
    <div class="small-12 columns">
      <%= yield %>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  
  <%= yield :extra_footer %>
</body>
</html>